### ISSUE TITLE
Adafruit HAT

### ISSUE THREAD

**Issue by sirago** [alexlukelevy/tickertape#5]
How does one go about setting --led-gpio-mapping=adafruit-hat ?

**Comment by alexlukelevy** [comment]
Unfortunately, the library would need to be modified to accept it as a command line argument ([example](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/bindings/python/samples/samplebase.py)).  Happy to accept PRs :)

Alternatively, if you want to fork it or modify the [source code](https://github.com/alexlukelevy/ticker-tape/blob/master/tickertape/tickertape.py#L41), then you can do something like the following.

```python
options = RGBMatrixOptions()
options.rows = 16
options.chain_length = 1
options.parallel = 1
options.hardware_mapping = 'adafruit-hat' 

matrix = RGBMatrix(options = options)
```
